[package]
name = "rusty_checker"
version = "0.1.4"
edition = "2024"
description = "A simple RowHammer vulnerability checker written in Rust"
license = "GPL-3.0"
repository = "https://github.com/KushalMeghani1644/Rusty-Checker"
homepage = "https://kushalmeghani1644.github.io/Rusty-Suite/"            # optional but helpful
keywords = ["rowhammer", "memory", "rust", "checker"]
categories = ["command-line-utilities", "development-tools::debugging"]
readme = "README.md"
authors = ["Kushal Meghani <kushalmeghani708@gmail.com>"]
[dependencies]
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ctrlc = "3.4"
clap = { version = "4.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.9.2"
thiserror = "2.0.16"
